"""Command-line interface for fm-saxml."""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Annotated, Optional

import typer
from rich.console import Console
from rich.progress import (
    BarColumn,
    Progress,
    SpinnerColumn,
    TaskProgressColumn,
    TextColumn,
    TimeElapsedColumn,
)
from rich.table import Table
from typer.core import TyperGroup


class _DefaultToBuildGroup(TyperGroup):
    """Let ``fm-saxml export.xml`` mean ``fm-saxml build export.xml``.

    Also makes drag-and-drop onto the executable work, since the OS passes
    the dropped file as the only argument.
    """

    def parse_args(self, ctx, args):
        if args and not args[0].startswith("-") and args[0] not in self.commands:
            args = ["build", *args]
        return super().parse_args(ctx, args)


app = typer.Typer(
    name="fm-saxml",
    cls=_DefaultToBuildGroup,
    help=(
        "Generate structured documentation from FileMaker Pro Save As XML exports.\n\n"
        "Quick start: fm-saxml MyExport.xml"
    ),
    no_args_is_help=True,
)
console = Console()
err_console = Console(stderr=True)


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_OUT_DIR_NAME = "saxml2doc"
DEFAULT_OUT_DIR = Path(DEFAULT_OUT_DIR_NAME)

# Dropped into every output directory so we can tell our own output from
# an unrelated folder before offering to wipe it.
OUTPUT_MARKER = ".fm-saxml"


def _default_out_dir(input_xml: Path) -> Path:
    """Default output: ``<input name>_docs`` next to the input file."""
    return input_xml.parent / f"{input_xml.stem}_docs"


def _fail(message: str, hint: str | None = None) -> "typer.Exit":
    err_console.print(f"[red]Error:[/red] {message}")
    if hint:
        err_console.print(f"[dim]{hint}[/dim]")
    raise typer.Exit(1)


def _open_folder(path: Path) -> None:
    """Open ``path`` in the platform's file manager (best effort)."""
    import subprocess

    try:
        if sys.platform == "win32":
            os.startfile(path)  # noqa: S606
        elif sys.platform == "darwin":
            subprocess.run(["open", str(path)], check=False)
        else:
            subprocess.run(["xdg-open", str(path)], check=False)
    except OSError:
        pass


# ---------------------------------------------------------------------------
# build: parse + render in one step
# ---------------------------------------------------------------------------

@app.command()
def build(
    input_xml: Annotated[Path, typer.Argument(help="FileMaker SaveAsXML file to process")],
    out: Annotated[Optional[Path], typer.Option("--out", "-o", help="Markdown output directory (defaults to <input name>_docs next to the input file)")] = None,
    model_out: Annotated[Optional[Path], typer.Option("--model-out", help="Path to write model.json")] = None,
    include_json: Annotated[bool, typer.Option("--include-json/--no-include-json", help="Write entities.json/references.json into docs dir")] = True,
    strict: Annotated[bool, typer.Option("--strict", help="Exit non-zero if there are unresolved references")] = False,
    force: Annotated[bool, typer.Option("--force", "-f", help="Overwrite the output directory without prompting")] = False,
    yes: Annotated[bool, typer.Option("--yes", "-y", help="Assume yes to all interactive prompts")] = False,
    open_when_done: Annotated[bool, typer.Option("--open", help="Open the output folder when finished")] = False,
) -> None:
    """Parse a FileMaker XML export and render Markdown documentation."""
    input_xml = _normalize_path(input_xml)
    out = _normalize_path(out) if out else _default_out_dir(input_xml)

    _validate_input(input_xml)
    _confirm_output_directory(out, force=force or yes)

    model = _run_pipeline(input_xml)

    if model_out:
        model_out = _normalize_path(model_out)
        from .render.json.writer import write_model_json
        write_model_json(model, model_out)
        console.print(f"[green]Model JSON written to {model_out}[/green]")

    _render_markdown_with_progress(model, out)
    console.print(f"[green]Markdown documentation written to {out}[/green]")

    if include_json:
        from .render.json.writer import write_split_json
        write_split_json(model, out)
        console.print(f"[dim]JSON data files written to {out}[/dim]")

    (out / OUTPUT_MARKER).write_text("Generated by fm-saxml. Safe to overwrite.\n", encoding="utf-8")

    _print_summary(model)
    if model.warnings:
        console.print(f"[dim]See {out / 'Reports' / 'warnings.md'} for details.[/dim]")

    if strict:
        unresolved = sum(1 for r in model.references if r.confidence == "unresolved")
        if unresolved:
            err_console.print(f"[red]--strict: {unresolved} unresolved references found[/red]")
            raise typer.Exit(1)

    if open_when_done:
        _open_folder(out)


# ---------------------------------------------------------------------------
# parse: XML → model.json
# ---------------------------------------------------------------------------

@app.command()
def parse(
    input_xml: Annotated[Path, typer.Argument(help="FileMaker SaveAsXML file")],
    out: Annotated[Path, typer.Option("--out", "-o", help="Output model.json path")] = Path("./build/model.json"),
) -> None:
    """Parse a FileMaker XML export and save the normalized model as JSON."""
    input_xml = _normalize_path(input_xml)
    out = _normalize_path(out)

    _validate_input(input_xml)
    model = _run_pipeline(input_xml)

    from .render.json.writer import write_model_json
    write_model_json(model, out)
    console.print(f"[green]Model JSON written to {out}[/green]")
    _print_summary(model)


# ---------------------------------------------------------------------------
# render: model.json → Markdown
# ---------------------------------------------------------------------------

@app.command()
def render(
    format: Annotated[str, typer.Argument(help="Output format: 'markdown'")] = "markdown",
    model_json: Annotated[Path, typer.Option("--model", "-m", help="Path to model.json")] = Path("./build/model.json"),
    out: Annotated[Path, typer.Option("--out", "-o", help="Output directory (defaults to ./saxml2doc)")] = DEFAULT_OUT_DIR,
    force: Annotated[bool, typer.Option("--force", "-f", help="Overwrite the output directory without prompting")] = False,
    yes: Annotated[bool, typer.Option("--yes", "-y", help="Assume yes to all interactive prompts")] = False,
) -> None:
    """Render an existing model.json into documentation."""
    model_json = _normalize_path(model_json)
    out = _normalize_path(out)

    if not model_json.exists():
        err_console.print(f"[red]Model file not found: {model_json}[/red]")
        raise typer.Exit(1)

    _confirm_output_directory(out, force=force or yes)

    import orjson
    from .model.document_model import DocumentModel

    raw = orjson.loads(model_json.read_bytes())
    model = DocumentModel.model_validate(raw)

    if format.lower() == "markdown":
        _render_markdown_with_progress(model, out)
        console.print(f"[green]Markdown documentation written to {out}[/green]")
    else:
        err_console.print(f"[red]Unknown format '{format}'. Supported: markdown[/red]")
        raise typer.Exit(1)


# ---------------------------------------------------------------------------
# inspect: print counts and warnings
# ---------------------------------------------------------------------------

@app.command()
def inspect(
    input_xml: Annotated[Path, typer.Argument(help="FileMaker SaveAsXML file")],
) -> None:
    """Parse a FileMaker XML export and print entity counts and warnings."""
    input_xml = _normalize_path(input_xml)
    _validate_input(input_xml)
    model = _run_pipeline(input_xml)
    _print_summary(model, verbose=True)


# ---------------------------------------------------------------------------
# validate: check model consistency
# ---------------------------------------------------------------------------

@app.command()
def validate(
    input_xml: Annotated[Path, typer.Argument(help="FileMaker SaveAsXML file")],
) -> None:
    """Parse and validate a FileMaker XML export, reporting any issues."""
    input_xml = _normalize_path(input_xml)
    _validate_input(input_xml)
    model = _run_pipeline(input_xml)

    error_warnings = [w for w in model.warnings if w.code not in ("UNUSED_FIELD_CANDIDATE",)]
    if error_warnings:
        console.print(f"[yellow]Validation found {len(error_warnings)} issue(s):[/yellow]")
        for w in error_warnings:
            console.print(f"  [{w.code}] {w.message}")
        raise typer.Exit(1)
    else:
        console.print("[green]Validation passed — no critical issues found.[/green]")


# ---------------------------------------------------------------------------
# diff: compare two exports (XML or model.json)
# ---------------------------------------------------------------------------

@app.command()
def diff(
    old_input: Annotated[Path, typer.Argument(help="Baseline: a SaveAsXML file or a previously-saved model.json")],
    new_input: Annotated[Path, typer.Argument(help="Comparison: a SaveAsXML file or a previously-saved model.json")],
    out: Annotated[Optional[Path], typer.Option("--out", "-o", help="Write a Markdown diff report to this path")] = None,
    strict: Annotated[bool, typer.Option("--strict", help="Exit non-zero if any difference is found")] = False,
) -> None:
    """Compare two FileMaker exports and report what changed between them."""
    old_input = _normalize_path(old_input)
    new_input = _normalize_path(new_input)
    _validate_input(old_input)
    _validate_input(new_input)

    old_model = _load_model_for_diff(old_input, label="baseline")
    new_model = _load_model_for_diff(new_input, label="comparison")

    from .analyze.diff import compute_diff
    result = compute_diff(old_model, new_model)

    _print_diff_summary(result)

    if out:
        out = _normalize_path(out)
        from .render.markdown.diff_renderer import render_diff_markdown
        render_diff_markdown(result, out)
        console.print(f"[green]Diff report written to {out}[/green]")

    if strict and result.has_changes:
        err_console.print("[red]--strict: differences were found[/red]")
        raise typer.Exit(1)


def _load_model_for_diff(path: Path, *, label: str):
    if path.suffix.lower() == ".json":
        import orjson
        from .model.document_model import DocumentModel
        console.print(f"[dim]Loading {label} model from {path}...[/dim]")
        raw = orjson.loads(path.read_bytes())
        return DocumentModel.model_validate(raw)
    return _run_pipeline(path)


def _print_diff_summary(result) -> None:
    tbl = Table(title="Diff Summary", show_header=True)
    tbl.add_column("Entity Type", style="cyan")
    tbl.add_column("Added", justify="right", style="green")
    tbl.add_column("Removed", justify="right", style="red")
    tbl.add_column("Changed", justify="right", style="yellow")
    for t in result.types:
        if t.has_changes:
            tbl.add_row(t.label, str(len(t.added)), str(len(t.removed)), str(len(t.changed)))
    console.print(tbl)

    if result.script_step_diffs:
        console.print(f"[dim]Scripts with step changes: {len(result.script_step_diffs)}[/dim]")

    if not result.has_changes:
        console.print("[green]No differences detected.[/green]")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _normalize_path(path: Path) -> Path:
    """Expand ~ and env vars and return an absolute Path.

    Works uniformly across Windows (drive letters, UNC paths like
    ``\\\\server\\share\\...``), macOS, and Linux because ``pathlib.Path`` is
    platform-aware: on Windows it's a ``WindowsPath``, on POSIX systems it's
    a ``PosixPath``. We avoid ``str.replace`` on separators or any
    platform-specific manipulation here.
    """
    if path is None:
        return path
    # Expand environment variables (e.g. %USERPROFILE%, $HOME) and ~
    import os
    expanded = os.path.expandvars(str(path))
    p = Path(expanded).expanduser()
    # Don't resolve() because it would fail on not-yet-created output dirs;
    # absolute() preserves intent without requiring the path to exist.
    if not p.is_absolute():
        try:
            p = p.absolute()
        except OSError:
            pass
    return p


def _validate_input(path: Path) -> None:
    if not path.exists():
        err_console.print(f"[red]Input file not found: {path}[/red]")
        raise typer.Exit(1)
    if not path.is_file():
        err_console.print(f"[red]Not a file: {path}[/red]")
        raise typer.Exit(1)


EXPORT_HINT = "In FileMaker Pro: Tools > Save a Copy as XML..., then run fm-saxml on that file."


def _confirm_output_directory(out_dir: Path, force: bool = False) -> None:
    """Ensure the output directory is empty, or get explicit user consent.

    Behavior:
    - If ``out_dir`` doesn't exist, do nothing (the renderer will create it).
    - If ``out_dir`` exists but is empty, do nothing.
    - If ``out_dir`` exists and is non-empty, prompt the user to overwrite
      (which clears the directory) or cancel. ``--force``/``--yes`` skip the
      prompt and overwrite.
    - If ``out_dir`` exists but is a file (not a directory), refuse.
    """
    if not out_dir.exists():
        return

    if out_dir.is_file():
        err_console.print(f"[red]Output path exists and is a file, not a directory: {out_dir}[/red]")
        raise typer.Exit(1)

    # Directory exists — check if empty
    try:
        is_empty = not any(out_dir.iterdir())
    except OSError as exc:
        err_console.print(f"[red]Cannot read output directory {out_dir}: {exc}[/red]")
        raise typer.Exit(1)

    if is_empty:
        return

    if force:
        _wipe_directory(out_dir)
        return

    console.print(f"[yellow]Output directory already exists and is not empty:[/yellow] {out_dir}")
    if not (out_dir / OUTPUT_MARKER).exists():
        console.print(
            "[bold red]Warning:[/bold red] this folder was not created by fm-saxml. "
            "Overwriting will delete everything in it."
        )
    choice = typer.prompt(
        "Overwrite contents (o), cancel (c)?",
        default="c",
        show_default=True,
    ).strip().lower()

    if choice in ("o", "overwrite", "y", "yes"):
        _wipe_directory(out_dir)
    else:
        console.print("[yellow]Cancelled. No files were written.[/yellow]")
        raise typer.Exit(0)


def _wipe_directory(out_dir: Path) -> None:
    """Remove every entry inside ``out_dir`` (the directory itself is preserved)."""
    for child in out_dir.iterdir():
        if child.is_symlink() or child.is_file():
            try:
                child.unlink()
            except OSError as exc:
                err_console.print(f"[red]Could not remove {child}: {exc}[/red]")
                raise typer.Exit(1)
        else:
            try:
                shutil.rmtree(child)
            except OSError as exc:
                err_console.print(f"[red]Could not remove {child}: {exc}[/red]")
                raise typer.Exit(1)


def _run_pipeline(input_xml: Path):
    from .parser.saxml_reader import parse_savexml
    from .normalize.normalize import normalize
    from .normalize.references import resolve_references
    from .analyze.backlinks import generate_backlinks
    from .analyze.warnings import generate_warnings
    from .model.validation import validate_model

    with _progress() as progress:
        task = progress.add_task(f"Parsing {input_xml.name}", total=6)
        raw = parse_savexml(input_xml)

        xml_errors = [w for w in raw.parse_warnings if w.startswith("XML parse error")]
        if xml_errors:
            _fail(f"'{input_xml.name}' is not valid XML ({xml_errors[0]}).", EXPORT_HINT)
        if not (raw.tables or raw.scripts or raw.layouts or raw.fields):
            _fail(f"'{input_xml.name}' doesn't contain any FileMaker tables, scripts or layouts.", EXPORT_HINT)

        progress.update(task, advance=1, description="Normalizing")
        model = normalize(raw, source_file=str(input_xml), source_path=input_xml)

        progress.update(task, advance=1, description="Resolving references")
        model = resolve_references(model)

        progress.update(task, advance=1, description="Generating backlinks")
        model = generate_backlinks(model)

        progress.update(task, advance=1, description="Generating warnings")
        model = generate_warnings(model)

        progress.update(task, advance=1, description="Validating model")
        model = validate_model(model)

        progress.update(task, advance=1, description=f"Analyzed {input_xml.name}")

    return model


def _progress() -> Progress:
    """Spinner + bar + elapsed time. Rich degrades gracefully when output is piped."""
    return Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        TimeElapsedColumn(),
        console=console,
    )


def _render_markdown_with_progress(model, out: Path) -> None:
    """Render Markdown, advancing a progress bar once per page written."""
    from .render.markdown.link_resolver import LinkResolver
    from .render.markdown.renderer import render_markdown
    from .utils.file_writer import on_write

    # Entity pages plus a rough allowance for section indexes and reports.
    total = LinkResolver(model).page_count + 25
    written = 0

    with _progress() as progress:
        task = progress.add_task("Writing pages", total=total)

        def tick(_path: Path) -> None:
            nonlocal written
            written += 1
            progress.update(task, completed=written, total=max(total, written))

        with on_write(tick):
            render_markdown(model, out)
        progress.update(task, completed=written, total=written, description=f"Wrote {written} pages")


def _print_summary(model, verbose: bool = False) -> None:
    em = model.entities
    tbl = Table(title="Entity Counts", show_header=True)
    tbl.add_column("Entity Type", style="cyan")
    tbl.add_column("Count", justify="right", style="green")
    rows = [
        ("Tables", len(em.tables)),
        ("Fields", len(em.fields)),
        ("Table Occurrences", len(em.table_occurrences)),
        ("Relationships", len(em.relationships)),
        ("Layouts", len(em.layouts)),
        ("Layout Objects", len(em.layout_objects)),
        ("Scripts", len(em.scripts)),
        ("Script Steps", len(em.script_steps)),
        ("Custom Functions", len(em.custom_functions)),
        ("Value Lists", len(em.value_lists)),
        ("Privilege Sets", len(em.privilege_sets)),
        ("Accounts", len(em.accounts)),
        ("Extended Privileges", len(em.extended_privileges)),
        ("Custom Menus", len(em.custom_menus)),
        ("Custom Menu Sets", len(em.custom_menu_sets)),
        ("Themes", len(em.themes)),
        ("File References", len(em.file_references)),
    ]
    for name, count in rows:
        tbl.add_row(name, str(count))
    console.print(tbl)

    unresolved = sum(1 for r in model.references if r.confidence == "unresolved")
    external = sum(1 for r in model.references if r.confidence == "external")
    console.print(f"[dim]References: {len(model.references)} total, {unresolved} unresolved, {external} external[/dim]")
    console.print(f"[dim]Warnings: {len(model.warnings)}[/dim]")

    if verbose and model.warnings:
        console.print("\n[yellow]Warnings:[/yellow]")
        from collections import Counter
        by_code = Counter(w.code for w in model.warnings)
        for code, count in by_code.most_common():
            console.print(f"  {code}: {count}")


# ---------------------------------------------------------------------------
# doctor: environment self-check
# ---------------------------------------------------------------------------

@app.command()
def doctor() -> None:
    """Print environment details useful for troubleshooting."""
    import platform
    import tempfile

    from lxml import etree

    console.print(f"fm-saxml     : {_package_version()}")
    console.print(f"Python       : {platform.python_version()} ({platform.python_implementation()})")
    console.print(f"Platform     : {platform.platform()}")
    console.print(f"lxml         : {etree.LXML_VERSION}")
    console.print(f"stdout enc.  : {sys.stdout.encoding}")
    console.print(f"Working dir  : {Path.cwd()}")
    try:
        with tempfile.TemporaryDirectory(dir=Path.cwd()):
            console.print("[green]Working directory is writable.[/green]")
    except OSError as exc:
        console.print(f"[red]Working directory is NOT writable: {exc}[/red]")
        raise typer.Exit(1)


def _package_version() -> str:
    from importlib.metadata import PackageNotFoundError, version

    try:
        return version("fm-saxml-converter")
    except PackageNotFoundError:
        return "unknown (not installed)"


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Console entry point: friendly one-line errors instead of tracebacks."""
    try:
        app()
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception as exc:  # noqa: BLE001
        if os.environ.get("FM_SAXML_DEBUG"):
            raise
        err_console.print(f"[red]Error:[/red] {exc}")
        err_console.print("[dim]Set FM_SAXML_DEBUG=1 for the full traceback.[/dim]")
        sys.exit(1)


if __name__ == "__main__":
    main()
